## 指定端口server:server:
server:
  port: 8080

## --------------- mybatis ---------------
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://192.168.1.124:3306/lixin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=true
    setValidationQuery: SELECT 1