## 指定端口server:server:
server:
  port: 8080

## --------------- mybatis ---------------
#spring:
#  datasource:
#    password: root
#    username: root
#    url: jdbc:mysql://192.168.25.128:3306/lixin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=true
#    driverClassName: com.mysql.cj.jdbc.Driver
#    setValidationQuery: SELECT 1

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://192.168.1.124:3306/lixin?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driverClassName: com.mysql.cj.jdbc.Driver
    setValidationQuery: SELECT 1

## --------------- logback ---------------
yes:
  server:
    logWorkDir: C:\Users\yuandian\Desktop\workspace\springboot-stage
    localHost: 8080
  log:
    version: 1.0.0
simplelii:
  env:
    module: springboot-stage
    logger:
      level: INFO

redis:
  test: test

## 指定日志实现
logging:
  config: classpath:logback-spring.xml
